grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer

  dashboards:
    java-app:
      json: |
        {{ .Files.Get "infra/monitoring/grafana-dashboard/java-app-dashboard.json" | indent 8 }}


    datasources:
      enabled: true

    additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack-dev.dev-monitoring-logging.svc.cluster.local:3100
      isDefault: false



prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'demo-javaapp'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['demo-javaapp.dev.svc.cluster.local:8080']

serviceMonitors:
  enabled: true
