grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"

    datasources:
      enabled: true
      
    additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack-dev.dev-monitoring-logging.svc.cluster.local:3100
      isDefault: false



prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'demo-javaapp'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['demo-javaapp.dev.svc.cluster.local:8080']

serviceMonitors:
  enabled: true
