apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-javaapp-dev-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app-dev.cloudandcosmos.com
      secretName: demo-javaapp-dev-tls
  rules:
    - host: app-dev.cloudandcosmos.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-javaapp-dev    
                port:
                  number: 80
