# grafana:
#   admin:
#     existingSecret: grafana-admin-secret
#     userKey: admin-user
#     passwordKey: admin-password
#   service:
#     type: LoadBalancer

# prometheus:
#   prometheusSpec:
#     retention: "30d"
