apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sangam-ghimire/DevSecOps-FullJavaPipeline.git
    targetRevision: main
    path: infra/monitoring/prometheus-stack-crds
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-logging
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      selfHeal: true
      prune: true
