

]

"

\
]


\
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sangam-ghimire/DevSecOps-FullJavaPipeline.git
    targetRevision: dev-environment
    path: k8s\

    \

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
\
