apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sangam-ghimire/DevSecOps-FullJavaPipeline.git
    targetRevision: prod-environment
    path: infra/logging/loki-stack
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-monitoring-logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
