apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-javaapp-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by: argocd
    argocd.argoproj.io/manifest-generate-paths: helm/demo-javaapp
    # argocd.argoproj.io/sync-options: CreateNamespace=true 
spec:
  project: default
  source:
    repoURL: https://github.com/Sangam-ghimire/DevSecOps-FullJavaPipeline.git
    targetRevision: prod-environment
    path: helm/demo-javaapp
    helm:
      valueFiles:
        - values-prod.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
