replicaCount: 3

image:
  repository: sangamghimire/demo-javaapp
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# env:
#   SPRING_PROFILES_ACTIVE: prod

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5

startupProbe:
  enabled: true
  httpGet:
    path: /startup
    port: http
  failureThreshold: 30
  periodSeconds: 5
