replicaCount: 3

image:
  repository: sangamghimire/demo-javaapp
  tag: dev-2009ce97524b3ad9d47b8f0747a3bf15cc2b3892
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

serviceAccount:
  create: true

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5

startupProbe:
  enabled: true
  httpGet:
    path: /startup
    port: http
  failureThreshold: 30
  periodSeconds: 5
