replicaCount: 1

image:
  repository: sangamghimire/demo-javaapp
  tag: prod-1.0.38
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

ingress:
  enabled: false  # Set to true if using ingress in cloud

serviceAccount:
  create: true  # Disable service account creation if not needed

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80  # Optional, for memory-based autoscaling

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  failureThreshold: 30
  periodSeconds: 5


createNamespace: false
namespace: prod

resources:
  requests:
    cpu: "400m"
    memory: "350Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
