replicaCount: 3

image:
  repository: sangamghimire/demo-javaapp
  tag: dev-1.0.31
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

serviceAccount:
  create: true

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  failureThreshold: 30
  periodSeconds: 5

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

createNamespace: false
namespace: dev



