# values.yaml
replicaCount: 1

image:
  repository: sangamghimire/demo-javaapp-optimized
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080

ingress:
  enabled: false  # Set to true if using ingress in cloud

serviceAccount:
  create: false  # Disable service account creation if not needed

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80  # Optional, for memory-based autoscaling

