name: CI/CD Dev Deployment

on:
  push:
    branches:
      - dev-environment
    paths:
      - 'demo-javaapp/**'
      - '.github/**'

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Read & Bump App Version
        id: bump
        run: |
          CURRENT_VERSION=$(cat VERSION)
          
          BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-.*//')
          MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_VERSION | cut -d. -f3)
          
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          echo "$NEW_VERSION" > VERSION
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Set Up JDK & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: |
          cd demo-javaapp
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image for Dev
        run: |
          VERSION="dev-${{ steps.bump.outputs.new_version }}"
          DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/demo-javaapp"

          docker build -t $DOCKER_IMAGE:$VERSION -f ./demo-javaapp/Dockerfile ./demo-javaapp
          docker tag $DOCKER_IMAGE:$VERSION $DOCKER_IMAGE:dev-latest

          docker push $DOCKER_IMAGE:$VERSION
          docker push $DOCKER_IMAGE:dev-latest

      - name: Update Helm Chart Values
        run: |
          VERSION="dev-${{ steps.bump.outputs.new_version }}"
          sed -i "s|repository:.*|repository: ${{ secrets.DOCKER_USERNAME }}/demo-javaapp|" helm/demo-javaapp/values-dev.yaml
          sed -i "s|tag:.*|tag: $VERSION|" helm/demo-javaapp/values-dev.yaml
      
      - name: Commit and Push VERSION + Helm Chart Updates
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add VERSION helm/demo-javaapp/values-dev.yaml
          git diff --cached --quiet || (git commit -m "chore: bump version to dev-${{ steps.bump.outputs.new_version }} and update Helm chart" && git push origin dev-environment)
      
      - name: Lint Helm Chart
        run: helm lint helm/demo-javaapp -f helm/demo-javaapp/values-dev.yaml
