name: CI/CD Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: |
          cd demo-javaapp
          mvn clean package -DskipTests

      - name: Log in to Docker Hub Securely
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image Securely
        run: |
          DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/demo-javaapp"
          IMAGE_TAG="dev-${{ github.sha }}"
          
          docker build --file demo-javaapp/Dockerfile -t $DOCKER_IMAGE:$IMAGE_TAG demo-javaapp
          docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest

          docker push $DOCKER_IMAGE:$IMAGE_TAG
          docker push $DOCKER_IMAGE:latest


      - name: Set Up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Push Helm Chart to Docker Hub Securely
        run: |
          helm registry login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          helm package helm/demo-javaapp
          helm push demo-javaapp-*.tgz oci://${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}

      - name: Deploy Helm Chart to Dev Kubernetes
        run: |
          helm upgrade --install demo-app oci://${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/demo-javaapp \
            --version $(grep 'version:' helm/demo-javaapp/Chart.yaml | awk '{print $2}') \
            -f helm/demo-javaapp/values-dev.yaml
