name: CI/CD Dev Deployment

on:
  push:
    branches:
      - dev-environment
    paths:
      - 'demo-javaapp/**'


jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Read App Version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"


      - name: Set Up JDK & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: |
          cd demo-javaapp
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image for Dev
        run: |
          DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/demo-javaapp"
          IMAGE_TAG="dev-${{ github.sha }}"
          
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG -f ./demo-javaapp/Dockerfile ./demo-javaapp
          docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:dev-latest

          docker push $DOCKER_IMAGE:$IMAGE_TAG
          docker push $DOCKER_IMAGE:dev-latest

      - name: Update Helm Chart Values
        run: |
          sed -i "s|repository:.*|repository: ${{ secrets.DOCKER_USERNAME }}/demo-javaapp|" helm/demo-javaapp/values-dev.yaml
          sed -i "s|tag:.*|tag: dev-${{ steps.version.outpus.version }}|" helm/demo-javaapp/values-dev.yaml
 
      - name: Lint Helm Chart
        run: helm lint helm/demo-javaapp -f helm/demo-javaapp/values-dev.yaml
