name: CI/CD Prod Deployment

on:
  push:
    branches:
      - prod-environment
    paths:
      - 'demo-javaapp/**'
      - '.github/**'

jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: |
          cd demo-javaapp
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image for Prod
        run: |
          DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/demo-javaapp"
          IMAGE_TAG="prod-${{ github.sha }}"
          
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG -f ./demo-javaapp/Dockerfile ./demo-javaapp
          docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:prod-latest

          docker push $DOCKER_IMAGE:$IMAGE_TAG
          docker push $DOCKER_IMAGE:prod-latest

      - name: Update Helm Chart Values
        run: |
          sed -i "s|repository:.*|repository: ${{ secrets.DOCKER_USERNAME }}/demo-javaapp|" helm/demo-javaapp/values-prod.yaml
          sed -i "s|tag:.*|tag: prod-${{ steps.version.outputs.version }}|" helm/demo-javaapp/values-prod.yaml

      - name: Commit and Push Helm Chart Updates
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add helm/demo-javaapp/values-prod.yaml
          git diff --cached --quiet || (git commit -m "chore: update Helm chart image tag to prod-${{ steps.version.output.version }}" && git push origin prod-environment)

 
      - name: Lint Helm Chart
        run: helm lint helm/demo-javaapp
