name: CI/CD Prod Deployment

on:
  push:
    branches:
      - prod-environment
    paths:
      - 'demo-javaapp/**'            # App source code
      - '.github/**'                 # CI configs

jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Read & Bump App Version
        id: bump
        run: |
          CURRENT_VERSION=$(cat VERSION)
          BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-.*//')
          MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "$NEW_VERSION" > VERSION
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Set Up JDK & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: |
          cd demo-javaapp
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image for Prod
        run: |
          VERSION="prod-${{ steps.bump.outputs.new_version }}"
          DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/demo-javaapp"

          docker build -t $DOCKER_IMAGE:$VERSION -f ./demo-javaapp/Dockerfile ./demo-javaapp
          docker push $DOCKER_IMAGE:$VERSION

      - name: Update Helm Chart Values
        run: |
          VERSION="prod-${{ steps.bump.outputs.new_version }}"
          sed -i "s|repository:.*|repository: ${{ secrets.DOCKER_USERNAME }}/demo-javaapp|" helm/demo-javaapp/values-prod.yaml
          sed -i "s|tag:.*|tag: $VERSION|" helm/demo-javaapp/values-prod.yaml
      
      - name: Bump Helm Chart Version
        run: |
          CHART_FILE="helm/demo-javaapp/Chart.yaml"

          CURRENT_CHART_VERSION=$(grep '^version:' "$CHART_FILE" | awk '{print $2}')
          BASE_CHART_VERSION=$(echo "$CURRENT_CHART_VERSION" | sed 's/-.*//')
          MAJOR=$(echo $BASE_CHART_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_CHART_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_CHART_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_CHART_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          # Update Chart.yaml
          sed -i "s/^version: .*/version: $NEW_CHART_VERSION/" "$CHART_FILE"

      - name: Commit and Push VERSION + Helm Chart Updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add VERSION helm/demo-javaapp/values-prod.yaml helm/demo-javaapp/Chart.yaml
          git diff --cached --quiet || (git commit -m "chore: bump version to prod-${{ steps.bump.outputs.new_version }} and update Helm chart [skip ci]" && git push origin prod-environment)

      - name: Lint Helm Chart
        run: helm lint helm/demo-javaapp -f helm/demo-javaapp/values-prod.yaml
